In [1]:
import numpy as np
from scipy.special import expit, softmax

In [42]:
w = [[1,-1],
     [-2,1]]
x = [0,7.4]

w, x = np.array(w), np.array(x)

s = np.matmul(w,x)

a = expit(s)

y = softmax(a)

print("wx:\n {}\nsigmoid:\n {}\nsoftmax:\n {}".format(s, a, y))

wx:
 [-7.4  7.4]
sigmoid:
 [6.10879359e-04 9.99389121e-01]
softmax:
 [0.2691817 0.7308183]


In [43]:
a=np.array([0,7.4])
softmax(a)

array([6.10879359e-04, 9.99389121e-01])

In [21]:
def convolution(img, kernel):
    img_size = img.shape[0]
    kernel_size = kernel.shape[0]
    new_img_size = img_size - kernel_size + 1
    # 準備新圖片
    new_img = np.zeros((new_img_size, new_img_size))
    
    # 經典雙迴圈
    for i in range(new_img_size):
        for j in range(new_img_size):
            value = 0
            # 經典雙雙迴圈 加大不加價(誤)
            # print(i,i+kernel_size)
            # print(img[i:i+kernel_size][j:j+kernel_size])
            new_img[i][j] = (img[i:i+kernel_size, j:j+kernel_size] * kernel).sum()
            
            # for ki in range(kernel_size):
            #     for kj in range(kernel_size):
            #         value += img[i+ki][j+kj] * kernel[ki][kj]
            # new_img[i][j] = value
    return new_img

In [40]:
img = [[0,0,0,0,0,0],
       [0,5,1,5,1,0],
       [0,5,1,5,1,0],
       [0,5,1,5,1,0],
       [0,5,1,5,1,0],
       [0,0,0,0,0,0]]

kernel = [[0,2,0],
          [2,-8,2],
          [0,2,0]]

img = np.array(img)
kernel = np.array(kernel)

# print(img.shape, kernel.shape)

outputs = convolution(img, kernel)

print('convolution:\n {}'.format(outputs))

convolution:
 [[-28.  14. -26.   4.]
 [-18.  16. -16.   6.]
 [-18.  16. -16.   6.]
 [-28.  14. -26.   4.]]
